-- O catálogo RBAC é integralmente versionado nas migrations. Nenhum papel,
-- grant ou página é criado aqui: isso mantém os 17 acessos comerciais ativos
-- reproduzíveis sem transformar fixtures locais em autoridade de produção.
