import { NextResponse } from "next/server";
import { cookies } from "next/headers";

import { hasFreshRecoveryAuthenticationMethod } from "@/lib/auth/mfa/assurance";
import { isRecoveryTokenHash, isSupabasePkceAuthCode } from "@/lib/auth/recovery-token";
import {
  buildSessionPersistenceCookie,
  issueSessionPersistence,
} from "@/lib/auth/session-persistence";
import { createClient } from "@/lib/auth/supabase/server";
import { noStoreHeaders } from "@/lib/security/api";
import { getApplicationUrl } from "@/lib/security/origin";

function recoveryRedirect(path: "/redefinir-senha" | "/esqueci-senha?status=invalid") {
  const destination = getApplicationUrl(path);
  if (!destination) {
    return new Response(null, { status: 503, headers: noStoreHeaders() });
  }

  return NextResponse.redirect(destination, {
    headers: noStoreHeaders({ "Referrer-Policy": "no-referrer" }),
  });
}

function isRecoveryRedirect(data: unknown) {
  return (
    typeof data === "object" &&
    data !== null &&
    "redirectType" in data &&
    data.redirectType === "recovery"
  );
}

export async function GET(request: Request) {
  if (!getApplicationUrl("/auth/callback")) {
    return new Response(null, { status: 503, headers: noStoreHeaders() });
  }

  const searchParams = new URL(request.url).searchParams;
  const tokenHash = searchParams.get("token_hash");
  const type = searchParams.get("type");
  const code = searchParams.get("code");
  const hasDirectRecoveryToken =
    code === null && type === "recovery" && isRecoveryTokenHash(tokenHash);
  const hasHostedPkceCode =
    tokenHash === null && (type === null || type === "recovery") && isSupabasePkceAuthCode(code);
  // Supabase Auth renders either the SHA-224 hash or its explicit `pkce_`
  // flow-prefixed form in `.TokenHash`. Hosted projects using the standard
  // ConfirmationURL instead return the one-time PKCE auth code generated by
  // GoTrue. Reject ambiguous/malformed callbacks before contacting Auth.
  if (!hasDirectRecoveryToken && !hasHostedPkceCode) {
    return recoveryRedirect("/esqueci-senha?status=invalid");
  }

  const supabase = await createClient({ persistence: { kind: "temporary" } });
  // Custom templates verify the token hash by POST/body. Hosted default mail
  // verifies at Supabase first, then this callback exchanges its PKCE code.
  // Nginx suppresses access/error logging for this exact callback location.
  let exchangeFailed = false;
  if (hasDirectRecoveryToken) {
    const { error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: "recovery",
    });
    exchangeFailed = error !== null;
  } else if (hasHostedPkceCode && isSupabasePkceAuthCode(code)) {
    const { data, error } = await supabase.auth.exchangeCodeForSession(code);
    exchangeFailed = error !== null || !isRecoveryRedirect(data);
    if (error === null && !isRecoveryRedirect(data)) {
      await supabase.auth.signOut({ scope: "local" });
    }
  } else {
    exchangeFailed = true;
  }

  // Invalid token hashes must not mutate a legitimate authenticated session
  // or its remember-browser marker. This also prevents logout-CSRF via a
  // syntactically valid but false callback URL.
  if (exchangeFailed) {
    return recoveryRedirect("/esqueci-senha?status=invalid");
  }

  // A successful recovery exchange always creates a temporary session. Clear
  // any previous remember-browser marker only after the token was verified.
  const marker = buildSessionPersistenceCookie(issueSessionPersistence(undefined));
  (await cookies()).set(marker.name, marker.value, marker.options);

  const { data, error } = await supabase.auth.getClaims();
  if (!error && hasFreshRecoveryAuthenticationMethod(data?.claims)) {
    return recoveryRedirect("/redefinir-senha");
  }

  await supabase.auth.signOut({ scope: "local" });
  return recoveryRedirect("/esqueci-senha?status=invalid");
}
