"use client";
import { useEffect, useState } from "react";
import { SiteMenu } from "./SiteMenu";
const fields = [{ key: "opportunities", label: "Oportunidades" }, { key: "appointments", label: "Agendamentos" }, { key: "visits", label: "Visitas" }, { key: "folders", label: "Pastas" }, { key: "sales", label: "Vendas" }] as const;
export function GoalsSettingsClient() {
  const [auth, setAuth] = useState(false); const [email, setEmail] = useState("contatoleandrolucass@gmail.com"); const [password, setPassword] = useState(""); const [values, setValues] = useState<Record<string, number>>({ opportunities: 0, appointments: 620, visits: 310, folders: 279, sales: 20 }); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/auth/session").then(r => { if (r.ok) { setAuth(true); fetch("/api/settings/goals").then(x => x.json()).then(row => row && setValues(v => ({ ...v, ...row }))); } }); }, []);
  async function login(e: React.FormEvent) { e.preventDefault(); setMessage("Entrando…"); const r = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!r.ok) { setMessage("Não foi possível entrar. Confirme o e-mail de acesso."); return; } setPassword(""); setAuth(true); setMessage("Acesso liberado."); const row = await fetch("/api/settings/goals").then(x => x.json()); if (row) setValues(v => ({ ...v, ...row })); }
  async function save(e: React.FormEvent) { e.preventDefault(); setMessage("Salvando…"); const r = await fetch("/api/settings/goals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); setMessage(r.ok ? "Metas salvas. O Dashboard usará os novos valores na próxima abertura." : "Falha ao salvar metas."); }
  return <main className="settings-shell"><SiteMenu /><section className="settings-card"><p className="eyebrow">Configurações / Metas</p><h1>Metas projetadas do funil</h1><p>Defina a meta mensal de cada etapa. O Dashboard permanece público; somente esta área exige acesso.</p>{!auth ? <form className="settings-form" onSubmit={login}><label>E-mail<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Senha<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="primary-link" type="submit">Entrar</button></form> : <form className="settings-form" onSubmit={save}>{fields.map(f => <label key={f.key}>{f.label}<input type="number" min="0" step="1" value={values[f.key]} onChange={e => setValues(v => ({ ...v, [f.key]: Number(e.target.value) }))} /></label>)}<button className="primary-link" type="submit">Salvar metas</button></form>}<p className="settings-message" role="status">{message}</p></section></main>;
}
